### ISSUE TITLE
enviroment.ylm not found

### ISSUE THREAD

**Issue by AlejandroLanaspa** [N-Nieto/Inner_Speech_Dataset#1]
Hi! Awesome work! I was trying to have a look at it but I am not finding the .ylm file, could you help me with that? Thanks!

**Comment by NeuroForLunch** [comment]
It's not included in the repo but I think you just need to install numpy, matplotlib, pickle, and mne.

**Comment by N-Nieto** [comment]
Hi Alejando, thank you so much! I'm thrilled that you can use the data.

I just upload the enviroment.yml.

I'm happy to answer any other question you may have regarding the scripts or the data.
