### ISSUE TITLE
Issues when loading subject 9 and 10

### ISSUE THREAD

**Issue by Jiang-Muyun** [N-Nieto/Inner_Speech_Dataset#10]
When loading the data, can successfully load subjects from 1 to 8, but there are loading errors of subjects 9 and 10.
Here is code that can reproduce the error.

```python
from Python_Processing.Data_extractions import  Extract_data_from_subject
root_dir = "../ds003626-download"
N_S = 9   # Subject number [1 to 10], 1 to 8 working fine, 9 and 10 have errors
X, Y = Extract_data_from_subject(root_dir, N_S, datatype="EEG")
```

![Screen Shot 2022-02-23 at 12 26 17 AM](https://user-images.githubusercontent.com/19842116/155175199-415c3daf-ac4a-4557-a491-9a1ad7c080ee.png)
![Screen Shot 2022-02-23 at 12 26 26 AM](https://user-images.githubusercontent.com/19842116/155175220-4f326f90-6bfd-4afa-a4e0-7bde8d5f379e.png)

**Comment by N-Nieto** [comment]
There were a problem with subject 9 and 10 in the data repository that was fixed in the last version of the dataset (2.1.0)

The problem should be solve if you download the data again: https://openneuro.org/datasets/ds003626/versions/2.1.0.

If the problem persist please reach me again.
