### ISSUE TITLE
Problem importing Raw

### ISSUE THREAD

**Issue by eduo123** [N-Nieto/Inner_Speech_Dataset#17]
Hello, I've been having problems trying to follow the new tutorial, 

----> 8 from Inner_Speech_Dataset.Python_Processing.Data_extractions import  extract_data_from_subject
      9 from Inner_Speech_Dataset.Python_Processing.Data_processing import  select_time_window, transform_for_classificator
     10 

[/content/Inner_Speech_Dataset/Python_Processing/Data_extractions.py](https://localhost:8080/#) in <module>
     14 from Inner_Speech_Dataset.Python_Processing.Utilitys import sub_name, unify_names       # noqa
     15 import pickle
---> 16 from mne.io.base import Raw
     17 
     18 

ImportError: cannot import name 'Raw' from 'mne.io.base' (/usr/local/lib/python3.10/dist-packages/mne/io/base.py)

I've trying updating mne but I can't find a Raw inside mne.io.base.

What might be going on?

Thanks in avance.

**Comment by N-Nieto** [comment]
Thanks for reporting the issue.

Is solved now.
