### ISSUE TITLE
Subject 6 Mystery

### ISSUE THREAD

**Issue by NeuroForLunch** [N-Nieto/Inner_Speech_Dataset#2]
How did you get such large file sizes for the derivatives from so little raw data?

<img width="621" alt="Screen Shot 2021-07-11 at 11 02 03 AM" src="https://user-images.githubusercontent.com/82769344/125208119-82340480-e245-11eb-9b29-c26780fffcff.png">

<img width="728" alt="Screen Shot 2021-07-11 at 10 59 46 AM" src="https://user-images.githubusercontent.com/82769344/125208115-7ea07d80-e245-11eb-87cd-d557ba101a9c.png">

<img width="1680" alt="Screen Shot 2021-07-11 at 10 54 38 AM" src="https://user-images.githubusercontent.com/82769344/125208126-8e1fc680-e245-11eb-809b-8de59503146d.png">

<img width="1680" alt="Screen Shot 2021-07-11 at 10 56 18 AM" src="https://user-images.githubusercontent.com/82769344/125208136-9841c500-e245-11eb-8cb2-03def05d037f.png">

<img width="1680" alt="Screen Shot 2021-07-11 at 10 59 11 AM" src="https://user-images.githubusercontent.com/82769344/125208139-9d067900-e245-11eb-8c75-a4ed75d64927.png">

**Comment by N-Nieto** [comment]
Thank you for your comments. There was a lot of corrupted data that was replaced in the new version of the dataset. 

Please check the new link.
https://openneuro.org/datasets/ds003626/versions/2.0.0/download

**Comment by NeuroForLunch** [comment]
Do you have any video footage of the data collection process?

**Comment by N-Nieto** [comment]
No, unfortunately I don't have any videos, the data collection process is described in  https://www.biorxiv.org/content/10.1101/2021.04.19.440473v1.

I will be happy to help you if you have any doubts.
