### ISSUE TITLE
Large variations in data quality

### ISSUE THREAD

**Issue by NeuroForLunch** [N-Nieto/Inner_Speech_Dataset#3]
<img width="1680" alt="full-timeline-s01-s01" src="https://user-images.githubusercontent.com/82769344/125208292-654c0100-e246-11eb-8f05-c46276a303ad.png">
<img width="1680" alt="full-timeline-s03-s01" src="https://user-images.githubusercontent.com/82769344/125208302-6da43c00-e246-11eb-9439-7937b4163ff8.png">
<img width="1680" alt="Screen Shot 2021-07-11 at 10 37 52 AM" src="https://user-images.githubusercontent.com/82769344/125208312-7268f000-e246-11eb-97e6-c692357e040e.png">
<img width="1680" alt="Screen Shot 2021-07-11 at 10 48 29 AM" src="https://user-images.githubusercontent.com/82769344/125208319-7432b380-e246-11eb-805f-51d6ad88601c.png">
<img width="1680" alt="Screen Shot 2021-07-11 at 10 49 39 AM" src="https://user-images.githubusercontent.com/82769344/125208326-77c63a80-e246-11eb-8bcf-c5c7b41fac48.png">
<img width="1680" alt="Screen Shot 2021-07-11 at 10 51 58 AM" src="https://user-images.githubusercontent.com/82769344/125208328-7bf25800-e246-11eb-8a01-fac6b2ac159e.png">
<img width="1680" alt="times-when-events-labeled-s01-s01" src="https://user-images.githubusercontent.com/82769344/125208339-86145680-e246-11eb-9a77-bf29f847b0a3.png">

The file sizes also show the difference:

<img width="692" alt="Screen Shot 2021-07-11 at 11 12 25 AM" src="https://user-images.githubusercontent.com/82769344/125208331-7f85df00-e246-11eb-83c5-3e62fede74eb.png">
<img width="684" alt="Screen Shot 2021-07-11 at 11 12 49 AM" src="https://user-images.githubusercontent.com/82769344/125208334-83196600-e246-11eb-83de-adf0fd608623.png">

**Comment by N-Nieto** [comment]
Same as before, thank you for your comments. 

Please check the new link for the repaired version of the dataset.
https://openneuro.org/datasets/ds003626/versions/2.0.0/download
