### ISSUE TITLE
This article is a preprint and has not been certified by peer review

### ISSUE THREAD

**Issue by NeuroForLunch** [N-Nieto/Inner_Speech_Dataset#4]
When do you think this article will be certified?

**Comment by N-Nieto** [comment]
Is under review now.

**Comment by N-Nieto** [comment]
You can access the final publication in the following link: https://www.nature.com/articles/s41597-022-01147-2

**Comment by NeuroForLunch** [comment]
You forgot to put me in the acknowledgements for reviewing and finding the data corruptions.
