### ISSUE TITLE
No module named 'Events_analysis'ModuleNotFoundError: No module named 'Events_analysis'

### ISSUE THREAD

**Issue by daazer** [N-Nieto/Inner_Speech_Dataset#5]

**Comment by N-Nieto** [comment]
The module "Events_analysis.py" is provided. Pleas check your execution root or provide further details.

**Comment by N-Nieto** [comment]
The module "Events_analysis.py" is provided, inside the Python_Processing folder. Pleas check your execution root or provide further details.
