### ISSUE TITLE
Problem with TRF_representations.py

### ISSUE THREAD

**Issue by daazer** [N-Nieto/Inner_Speech_Dataset#6]
Hello there
I have recently been trying to run this code using conda on windows. 
I have installed all the necessary libraries from the given yaml file.
When try to run, this error show up. 
Is there something wrong with the thing I'm doing?
Here is a picture of what I've been going through
![image](https://user-images.githubusercontent.com/19170627/137550224-470fadb6-90be-4d7a-85de-7f741286a875.png)

**Comment by N-Nieto** [comment]
Hey Daazer, sorry for the late response. Did you solve this?

I re-install all from scratch and I'm not having this problem.  I'm using the library right now and the load stage works fine. Can you tell me the exact pickle and numpy version you have  ?

**Comment by N-Nieto** [comment]
This is a data problem, check for corrupted files.
