### ISSUE TITLE
problem with ./InnerSpeech_preprocessing.py

### ISSUE THREAD

**Issue by daazer** [N-Nieto/Inner_Speech_Dataset#7]
While tried to run InnterSpeech_preprocessing.py
using the command below
_python ./InnterSpeech_preprocessing.py_
I confronted with this error message, claiming that the problem lies here

> invalid literal for int() with base 10: 'z-index:'

![image](https://user-images.githubusercontent.com/19170627/137550575-53fcf6ac-c2a3-4930-8b4b-e2e325925a6d.png)

The same problem happens when trying to run it on google colab.
![image](https://user-images.githubusercontent.com/19170627/137551077-df267bf0-74e5-4c6d-b16b-0d2782d913d6.png)

May anyone tell me what is wrong with it?

**Comment by N-Nieto** [comment]
Hello again, sorry for the late response. Did you solve this?

Can you send me the value and type of variables N_S and N_B?

**Comment by N-Nieto** [comment]
This is a Data problem, it could happen if it was a problem with the download process. You should check the size of the files and re-download those corrupted files.
